"""
AETHER backend API.

Run with:
    uvicorn main:app --reload --port 8000

Endpoints:
    GET  /api/summary              -> aggregate stats across all monitored zones
    GET  /api/feature-importance   -> global Random Forest feature importance
    GET  /api/zones                -> all monitored zones with predictions + SHAP + recommendations
    GET  /api/zones/{zone_id}      -> single zone detail
    POST /api/predict              -> live prediction for an arbitrary feature vector
    GET /api/model-metrics         -> returns the value of the metrics.json artifact generated by AI folder
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from app.config import API_TITLE, API_VERSION
from app.routes.health import router as health_router   
from app.lifespan import lifespan
from app.routes.metrics import router as metrics_router
from app.routes.prediction import (router as prediction_router)
from app.routes.zones import (
    router as zones_router
)
from app.routes.feature_importance import router as feature_importance_router
from app.routes.summary import router as summary_router


app = FastAPI(
    title=API_TITLE,
    version=API_VERSION,
    lifespan=lifespan
)

# Allows the Next.js frontend (running on a different port, hence a
# different origin as far as the browser is concerned) to call this API.
# Without this, the browser blocks every request with a CORS error even
# though the server itself responds fine — Postman/curl don't hit this
# restriction since it's enforced by browsers, not the server.
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(health_router)
app.include_router(prediction_router)
app.include_router(metrics_router)
app.include_router(zones_router)
app.include_router(feature_importance_router)
app.include_router(summary_router)


@app.get("/")
def root():
    return {
        "message": "Welcome to AETHER API",
        "version": API_VERSION,   
    }