"""
AETHER backend API.

Run with:
    uvicorn main:app --reload --port 8000

Endpoints:
    GET  /api/summary              -> aggregate stats across all monitored zones
    GET  /api/feature-importance   -> global Random Forest feature importance
    GET  /api/zones                -> all monitored zones with predictions + SHAP + recommendations
    GET  /api/zones/{zone_id}      -> single zone detail
    POST /api/predict              -> live prediction for an arbitrary feature vector
    GET /api/model-metrics         -> returns the value of the metrics.json artifact generated by AI folder
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from app.config import API_TITLE, API_VERSION
from app.routes.health import router as health_router   
from app.lifespan import lifespan
from app.routes.metrics import router as metrics_router
from app.routes.prediction import router as prediction_router
from app.routes.feature_importance import router as feature_importance_router


app = FastAPI(
    title=API_TITLE,
    version=API_VERSION,
    lifespan=lifespan
)

# Allow the Next.js dev server (and any origin in dev) to call the API
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "http://127.0.0.1:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(health_router,             prefix="/api")
app.include_router(prediction_router,         prefix="/api")
app.include_router(metrics_router,            prefix="/api")
app.include_router(feature_importance_router, prefix="/api")

@app.get("/")
def root():
    return {
        "message": "Welcome to AETHER API",
        "version": API_VERSION,   
    }