"""
AETHER backend API.

Run with:
    uvicorn app.main:app --reload --port 8000

Endpoints:
    GET  /api/summary              -> aggregate stats across all monitored zones
    GET  /api/feature-importance   -> global Random Forest feature importance
    GET  /api/zones                -> all monitored zones with predictions + SHAP + recommendations
    GET  /api/zones/{zone_id}      -> single zone detail
    POST /api/predict              -> live prediction for an arbitrary feature vector
    GET /api/model-metrics         -> returns the value of the metrics.json artifact generated by AI folder
"""

from fastapi import FastAPI

app = FastAPI(
    title="AETHER API",
    version="1.0.0"
)


@app.get("/")
def root():
    return {
        "message": "Welcome to AETHER API",
        "version": "1.0.0"
    }


@app.get("/health")
def health():
    return {
        "status": "healthy"
    }