// SEED DATA for monitored zones — stands in for the AI model's feature
// table until a real endpoint exists (see AI/data/raw/processed/feature_table.csv
// for the eventual real source). Zone ids here are shared with
// lib/mockRehabilitation.ts's SEED_ACTIVITIES, so a zone's map marker, KPI
// figures, and rehabilitation history all refer to the same place.

import type { ZoneSummary } from "./types";

export const MOCK_ZONES: ZoneSummary[] = [
  {
    zone_id: "ESTANCIA-0001",
    lat: 11.20,
    lon: 123.02,
    vulnerability_score: 4.35,
    risk_class: "high",
    confidence_flag: "ok",
    municipality: "Estancia",
    expected_area_loss: 2.6,
    rehabilitation_status: "Completed",
    top_factors: [{ label: "NDVI decline", value: 0.42 }, { label: "High temp", value: 0.31 }],
    recommendations: [
      "Deploy mangrove seedlings along the eroding shoreline segment.",
      "Continue post-rehabilitation NDVI monitoring on a quarterly basis.",
    ],
  },
  {
    zone_id: "ANILAO-0001",
    lat: 10.75,
    lon: 122.28,
    vulnerability_score: 2.95,
    risk_class: "moderate",
    confidence_flag: "ok",
    municipality: "Anilao",
    expected_area_loss: 1.3,
    rehabilitation_status: "Active",
    top_factors: [{ label: "Aquaculture proximity", value: 0.38 }],
    recommendations: [
      "Establish a buffer zone between aquaculture ponds and mangrove edge.",
      "Monitor water salinity levels monthly.",
    ],
  },
  {
    zone_id: "ESTANCIA-0003",
    lat: 11.15,
    lon: 122.95,
    vulnerability_score: 3.98,
    risk_class: "high",
    confidence_flag: "low",
    municipality: "Estancia",
    expected_area_loss: 2.1,
    rehabilitation_status: "Active",
    top_factors: [{ label: "NDVI decline", value: 0.39 }, { label: "Aquaculture proximity", value: 0.27 }],
    recommendations: [
      "Prioritize replanting in the segment with steepest NDVI decline.",
      "Coordinate with nearby aquaculture operators to reduce runoff.",
      "Validate satellite readings with a field survey given low confidence flag.",
    ],
  },
  {
    zone_id: "ZARRAGA-0001",
    lat: 10.85,
    lon: 122.58,
    vulnerability_score: 2.60,
    risk_class: "moderate",
    confidence_flag: "ok",
    municipality: "Zarraga",
    expected_area_loss: 1.1,
    rehabilitation_status: "Planned",
    top_factors: [{ label: "River proximity", value: 0.29 }],
    recommendations: [
      "Assess upstream sediment load contributing to riverbank erosion.",
      "Schedule planting activities ahead of the next dry season.",
    ],
  },
  {
    zone_id: "CARLES-0001",
    lat: 11.22,
    lon: 123.03,
    vulnerability_score: 3.05,
    risk_class: "moderate",
    confidence_flag: "ok",
    municipality: "Carles",
    expected_area_loss: 1.4,
    rehabilitation_status: "Planned",
    top_factors: [{ label: "Wind speed", value: 0.33 }],
    recommendations: [
      "Consider windbreak planting along the exposed shoreline.",
      "Reassess after the next monsoon season.",
    ],
  },
  {
    zone_id: "CARLES-0002",
    lat: 11.18,
    lon: 122.98,
    vulnerability_score: 1.05,
    risk_class: "low",
    confidence_flag: "ok",
    municipality: "Carles",
    expected_area_loss: 0.4,
    rehabilitation_status: "Completed",
    top_factors: [{ label: "Slope", value: 0.20 }],
    recommendations: ["Continue routine quarterly monitoring."],
  },
  {
    zone_id: "BANATE-0003",
    lat: 11.05,
    lon: 122.85,
    vulnerability_score: 4.10,
    risk_class: "high",
    confidence_flag: "ok",
    municipality: "Banate",
    expected_area_loss: 2.3,
    rehabilitation_status: "Under Review",
    top_factors: [{ label: "Aquaculture proximity", value: 0.41 }, { label: "High temp", value: 0.26 }],
    recommendations: [
      "Review current rehabilitation plan for adequacy given high vulnerability.",
      "Engage aquaculture operators on runoff mitigation measures.",
    ],
  },
  {
    zone_id: "ILOILOCITY-0003",
    lat: 10.70,
    lon: 122.56,
    vulnerability_score: 2.40,
    risk_class: "moderate",
    confidence_flag: "low",
    municipality: "Iloilo City",
    expected_area_loss: 1.0,
    rehabilitation_status: "Under Review",
    top_factors: [{ label: "Road proximity", value: 0.24 }],
    recommendations: [
      "Validate satellite readings with a field survey given low confidence flag.",
      "Assess road runoff impact on adjacent mangrove edge.",
    ],
  },
  // Monitored zones with no rehabilitation history yet — present on the map
  // and in KPI totals, but absent from the Rehabilitation Activities
  // repository (which only lists zones with at least one logged activity).
  {
    zone_id: "SARA-0001",
    lat: 11.10,
    lon: 122.75,
    vulnerability_score: 0.80,
    risk_class: "low",
    confidence_flag: "ok",
    municipality: "Sara",
    expected_area_loss: 0.2,
    rehabilitation_status: "None",
    top_factors: [{ label: "Slope", value: 0.15 }],
    recommendations: ["No action needed — maintain current monitoring schedule."],
  },
  {
    zone_id: "DUMANGAS-0001",
    lat: 10.83,
    lon: 122.70,
    vulnerability_score: 2.15,
    risk_class: "moderate",
    confidence_flag: "ok",
    municipality: "Dumangas",
    expected_area_loss: 0.9,
    rehabilitation_status: "None",
    top_factors: [{ label: "River proximity", value: 0.22 }],
    recommendations: [
      "Consider a scoping visit given river-proximity risk with no prior activity.",
    ],
  },
];